#!/bin/sh

  INVALID_SEMANTIC_ERR="./src/test/examples/invalid/semanticErr"
  INVALID_SEMANTIC_ERR_LOG="./log/parse_invalid_semantic_error.log"

for file in $(find $INVALID_SEMANTIC_ERR -name "*.wacc") 
do 
  ./grun antlr.WACC program -tree $file 2> $INVALID_SEMANTIC_ERR_LOG
  if grep "line [0-9]*:[0-9]*" $INVALID_SEMANTIC_ERR_LOG > /dev/null; then
    echo "expecting no error but found the following:"
    cat $INVALID_SEMANTIC_ERR_LOG
    echo $file 
    exit 1
  fi
done