#!/bin/sh

  INVALID_SYNTAX_ERR="./src/test/examples/invalid/syntaxErr"
  INVALID_SYNTAX_ERR_LOG="./log/parse_invalid_syntax_error.log"

for file in $(find $INVALID_SYNTAX_ERR -name "*.wacc") 
do 
  ./grun antlr.WACC program -tree $file 2> $INVALID_SYNTAX_ERR_LOG
  if ! grep "line [0-9]*:[0-9]*" $INVALID_SYNTAX_ERR_LOG > /dev/null; then
    echo "expecting errors but the following has none:"
    cat $INVALID_SYNTAX_ERR_LOG
    echo $file 
    exit 1
  fi
done
