#!/bin/sh

  VALID_EXAMPLES="./src/test/examples/valid"
  VALID_EXAMPLES_LOG="./log/parse_valid_error.log"

for file in $(find $VALID_EXAMPLES -name "*.wacc") 
do 
  ./grun antlr.WACC program -tree $file 2> $VALID_EXAMPLES_LOG
  if grep "line [0-9]*:[0-9]*" $VALID_EXAMPLES_LOG > /dev/null; then
    echo "expecting no error but found the following:"
    cat $VALID_EXAMPLES_LOG
    echo $file 
    exit 1
  fi
done