#!/bin/bash

# execute all tests
./scripts/parserTestValid
./scripts/parserTestSynErr
./scripts/parserTestSemanticErr
./scripts/semanticCheckerValid
./scripts/semanticCheckerSemanticErr
./scripts/assembleTest.sh
./scripts/executeTest.sh
./scripts/constantPropagation.sh 
./scripts/extensionValidTest.sh