#!/bin/sh

INVALID_SYNTAX_ERR="./src/test/examples/invalid/syntaxErr"
INVALID_PARSER_SYNTAX_ERR_LOG="./log/parse_invalid_syntax_error.log"

> $INVALID_PARSER_SYNTAX_ERR_LOG

for file in $(find $INVALID_SYNTAX_ERR -name "*.wacc")
do
  ./compile $file 2>> $INVALID_PARSER_SYNTAX_ERR_LOG
  ret=$?
  echo "exit status: " $ret
  if [ $ret -ne 100 ]; then
    echo "status code incorrect: " $ret
    exit 1
  fi
  
  if ! grep "line [0-9]*:[0-9]*" $INVALID_PARSER_SYNTAX_ERR_LOG > /dev/null; then
    echo "expecting error but found none:"
    exit 1
  fi
done