#!/bin/sh

INVALID_SEMANTIC_ERR="./src/test/examples/invalid/semanticErr"
INVALID_PARSER_SEMANTIC_ERR_LOG="./log/parse_invalid_semantic_error.log"

./grun antlr.WACC program -tree $(find $INVALID_SEMANTIC_ERR -name "*.wacc") 2> $INVALID_PARSER_SEMANTIC_ERR_LOG

if grep "line [0-9]*:[0-9]*" $INVALID_PARSER_SEMANTIC_ERR_LOG > /dev/null; then
  echo "expecting no error but found the following:"
  cat $INVALID_PARSER_SEMANTIC_ERR_LOG
  exit 1
fi