#!/bin/sh

INVALID_SYNTAX_ERR="./src/test/examples/invalid/syntaxErr"
INVALID_PARSER_SYNTAX_ERR_LOG="./log/parse_invalid_syntax_error.log"

./grun antlr.WACC program -tree $(find $INVALID_SYNTAX_ERR -name "*.wacc") 2> $INVALID_PARSER_SYNTAX_ERR_LOG

# if grep "line [0-9]*:[0-9]*" $INVALID_PARSER_SYNTAX_ERR_LOG > /dev/null; then
#   echo "inproper errors generated:"
#   cat $INVALID_PARSER_SYNTAX_ERR_LOG
#   exit 1
# fi