#!/bin/sh

INVALID_SYNTAX_ERR="./src/test/examples/invalid/syntaxErr"
INVALID_CHECKER_SYNTAX_ERR_LOG="./log/checker_invalid_syntax_error.log"

./compile $(find $INVALID_SYNTAX_ERR -name "*.wacc")  2> $INVALID_CHECKER_SYNTAX_ERR_LOG

# if grep "line [0-9]*:[0-9]*" $INVALID_CHECKER_SYNTAX_ERR_LOG > /dev/null; then
#   echo "incorrect syntax/semantic error generated:"
#   cat $INVALID_CHECKER_SYNTAX_ERR_LOG
#   echo $file 
#   exit 1
# fi