#!/bin/sh

VALID_EXAMPLES="./src/test/examples/valid"
VALID_CHECKER_EXAMPLES_LOG="./log/checker_valid_error.log"

> $VALID_CHECKER_EXAMPLES_LOG

for file in $(find $VALID_EXAMPLES -name "*.wacc") 
do 
  ./compile $file 2>> $VALID_CHECKER_EXAMPLES_LOG
  ret=$?
  if [ $ret -ne 0 ]; then
    echo "status code incorrect: " $ret
    exit 1
  fi
  echo "exit code: " $ret
  if grep "line [0-9]*:[0-9]*" $VALID_CHECKER_EXAMPLES_LOG > /dev/null || grep "Exception" $VALID_CHECKER_EXAMPLES_LOG > /dev/null; then
    echo "expecting no error but found the following:"
    cat $VALID_CHECKER_EXAMPLES_LOG
    echo $file 
    exit 1
  fi
done
