#!/bin/sh

INVALID_SEMANTIC_ERR="./src/test/examples/invalid/semanticErr"
INVALID_CHECKER_SEMANTIC_ERR_LOG="./log/checker_invalid_semantic_error.log"

./compile $(find $INVALID_SEMANTIC_ERR -name "*.wacc") 2> $INVALID_CHECKER_SEMANTIC_ERR_LOG

# if grep "line [0-9]*:[0-9]*" $INVALID_CHECKER_SEMANTIC_ERR_LOG > /dev/null; then
#   echo "incorrrect error has been generated:"
#   cat $INVALID_CHECKER_SEMANTIC_ERR_LOG
#   echo $file
#   exit 1
# fi