#!/bin/sh

INVALID_SEMANTIC_ERR="./src/test/examples/invalid/semanticErr"
INVALID_CHECKER_SEMANTIC_ERR_LOG="./log/checker_invalid_semantic_error.log"

> $INVALID_CHECKER_SEMANTIC_ERR_LOG

for file in $(find $INVALID_SEMANTIC_ERR -name "*.wacc")
do
  ./compile $file 2>> $INVALID_CHECKER_SEMANTIC_ERR_LOG
  ret=$?
  echo "exit status: " $ret
  if [ $ret -ne 200 ]; then
    echo "status code incorrect: " $ret
    exit 1
  fi
  
  if ! grep "line [0-9]*:[0-9]*" $INVALID_CHECKER_SEMANTIC_ERR_LOG > /dev/null; then
    echo "expecting error but the following has none:"
    cat $INVALID_CHECKER_SEMANTIC_ERR_LOG
    echo $file
    exit 1
  fi
done